[project]
name = "telethon-base"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pysocks>=1.7.1",
    "telethon>=1.41.2",
]
